### ISSUE TITLE
toolbarItems incorrect if the mouse is moved fast

### ISSUE THREAD

**Issue by cwolcott** [neuhausi/canvasXpress#205]
I have been noticing if I move the mouse north out of the canvas fast the toolbarItems display all of the options rather than what I defined.
`toolbarItems:        ['Save', 'Explore', 'Customize', 'Maximize'],`

Here is a [jsfiddle](https://jsfiddle.net/woolycew65/p1du6ech/2/) example.

![Image](https://github.com/user-attachments/assets/1880ed66-6660-4448-aceb-c9d0a8f2c941)
|-

When moving the mouse north out of the canvas slowly the toolbarItems display correctly.
![Image](https://github.com/user-attachments/assets/716a8284-6b70-4c04-8609-447a41a10a0b)
|-

**Comment by neuhausi** [comment]
Can you create a movie? I can't reproduce

**Comment by cwolcott** [comment]
Made this movie from the jsfiddle example mentioned above

https://github.com/user-attachments/assets/006ec3e4-4b9e-45af-9ed9-252f79d3da53

**Comment by neuhausi** [comment]
Wow. This is going to be a tough one.

**Comment by neuhausi** [comment]
Found it.. Racing conditions. Fixed in next version.

**Comment by cwolcott** [comment]
Here is another [jsfiddle](https://jsfiddle.net/woolycew65/p1du6ech/19/) example.
Move your mouse from right to left in the lower 1/3 of the chart.

https://github.com/user-attachments/assets/b8fdea00-5163-4e7c-b227-e1d1ef86c9af

**Comment by neuhausi** [comment]
I think I fix it. Version 55.1

**Comment by neuhausi** [comment]
Can you please check and close

**Comment by cwolcott** [comment]
I upgraded the [jsfiddle](https://jsfiddle.net/woolycew65/p1du6ech/20/) to use v55.2.

The toolbarItems (top) no longer displays items not in the config when moving the mouse to fast out of the canvas, but the toolbars still don't disappear when moving from canvas to canvas.  See the video above and try it with the latest jsfiddle that references v55.2.  Notice how the toolbarCodes don't disappear when you leave a canvas into enter another canvas.

The also occurs with the toolbarItems if I stack canvases on top of each other.

**Comment by cwolcott** [comment]
Yep, I was to impatient.  Works like you stated.
